from KekikSpatula import KekikTube

yt = KekikTube("https://www.youtube.com/watch?v=Kj26pD3uqn0")

print(yt.veri)
"""
json verisi döndürür

{'kaynak': 'Youtube.com', 'veri': [{'sahip': 'melek mosso', 'baslik': 'Ah be Aysel - Full Libido', 'sure': '3 dakika, 3 saniye', 'tarih': '09-06-2017', 'izlenme': 2759361, 'resim': 'https://i.ytimg.com/vi/Kj26pD3uqn0/maxresdefault.jpg', 'aciklama': 'Buram buram kadın kokan şarkılarla karşınızdayız :)\nSöz-müzik : Melek Mosso\nGitar : Veys Colak\nKlip  Yönetmenİ  :  Cansu İnceay\n\nFULL LİBİDO\n\nKaç gündür gelcem dedin gelmedin\nÇok içsem de kimseye vermedim\nIsrar ettim şansımı zorladım \nSabaha kadar ağladım duymadın\n\nBana hödö hödö yapma, çocuk mu var karşında\nSev beni daha ne diyim, söz hiç karışmam sana\nBen boşa trip atmam ama hormonlarım coştu\nŞu sıralar full libido, şu sıralar full libido \n\nOdamı temizledim süsüm püsüm hep sana\nİçli köfte yaptım tadına baksana\nBugün de aradım gelmezsen ayıp ama\nÇalışkan çocuksun maşallah sana \n\nM.Mosso', 'kalite': '360p', 'boyut': '11.23 MB', 'url': 'https://r6---sn-u0g3jxaa-n5fl.googlevideo.com/videoplayback?expire=1607062757&ei=hYDJX5z7E8-cgQfz8o-IBg&ip=176.227.67.18&id=o-AKNCEhdBVxmQnp75jl46ZET7tpAVzJ9XU5RXaJyEZLDB&itag=18&source=youtube&requiressl=yes&mh=dF&mm=31%2C29&mn=sn-u0g3jxaa-n5fl%2Csn-nv47lnsd&ms=au%2Crdu&mv=m&mvi=6&pl=24&pcm2=yes&initcwndbps=1035000&vprv=1&mime=video%2Fmp4&ns=CG1xG_s8KRkLtsxBJMEF2NIF&gir=yes&clen=11773185&ratebypass=yes&dur=182.532&lmt=1540930908202011&mt=1607040758&fvip=2&c=WEB&txp=5431432&n=3uOEOpBOw_gU7ToP5&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgfyLaBTQ5vysRiWCrlfK-9Po-4kn4tayXcdFSzcU0BDMCIEYaCczotXXwNXqX7Vfcl3U4Ofjasgt0PynQtlUtq6jQ&sig=AOq0QJ8wRgIhALrgDY1aqV3oKu1fGR5O1kG59a3SwKOS0z3jgiVTv592AiEAwysdv3Xqn45XU7BZ2TuB9qWtyYMfDNTizqzSeSR712s='}]}
"""

print(yt.nesne.url)
"""
json verisini python nesnesine dönüştürür.

https://r6---sn-u0g3jxaa-n5fl.googlevideo.com/videoplayback?expire=1607062757&ei=hYDJX5z7E8-cgQfz8o-IBg&ip=176.227.67.18&id=o-AKNCEhdBVxmQnp75jl46ZET7tpAVzJ9XU5RXaJyEZLDB&itag=18&source=youtube&requiressl=yes&mh=dF&mm=31%2C29&mn=sn-u0g3jxaa-n5fl%2Csn-nv47lnsd&ms=au%2Crdu&mv=m&mvi=6&pl=24&pcm2=yes&initcwndbps=1035000&vprv=1&mime=video%2Fmp4&ns=CG1xG_s8KRkLtsxBJMEF2NIF&gir=yes&clen=11773185&ratebypass=yes&dur=182.532&lmt=1540930908202011&mt=1607040758&fvip=2&c=WEB&txp=5431432&n=3uOEOpBOw_gU7ToP5&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgfyLaBTQ5vysRiWCrlfK-9Po-4kn4tayXcdFSzcU0BDMCIEYaCczotXXwNXqX7Vfcl3U4Ofjasgt0PynQtlUtq6jQ&sig=AOq0QJ8wRgIhALrgDY1aqV3oKu1fGR5O1kG59a3SwKOS0z3jgiVTv592AiEAwysdv3Xqn45XU7BZ2TuB9qWtyYMfDNTizqzSeSR712s=
"""

print(yt.gorsel())
"""
oluşan json verisini insanın okuyabileceği formatta döndürür.

{
  "kaynak": "Youtube.com",
  "veri": [
    {
      "sahip": "melek mosso",
      "baslik": "Ah be Aysel - Full Libido",
      "sure": "3 dakika, 3 saniye",
      "tarih": "09-06-2017",
      "izlenme": 2759361,
      "resim": "https://i.ytimg.com/vi/Kj26pD3uqn0/maxresdefault.jpg",
      "aciklama": "Buram buram kadın kokan şarkılarla karşınızdayız :)\nSöz-müzik : Melek Mosso\nGitar : Veys Colak\nKlip  Yönetmenİ  :  Cansu İnceay\n\nFULL LİBİDO\n\nKaç gündür gelcem dedin gelmedin\nÇok içsem de kimseye vermedim\nIsrar ettim şansımı zorladım \nSabaha kadar ağladım duymadın\n\nBana hödö hödö yapma, çocuk mu var karşında\nSev beni daha ne diyim, söz hiç karışmam sana\nBen boşa trip atmam ama hormonlarım coştu\nŞu sıralar full libido, şu sıralar full libido \n\nOdamı temizledim süsüm püsüm hep sana\nİçli köfte yaptım tadına baksana\nBugün de aradım gelmezsen ayıp ama\nÇalışkan çocuksun maşallah sana \n\nM.Mosso",
      "kalite": "360p",
      "boyut": "11.23 MB",
      "url": "https://r6---sn-u0g3jxaa-n5fl.googlevideo.com/videoplayback?expire=1607062757&ei=hYDJX5z7E8-cgQfz8o-IBg&ip=176.227.67.18&id=o-AKNCEhdBVxmQnp75jl46ZET7tpAVzJ9XU5RXaJyEZLDB&itag=18&source=youtube&requiressl=yes&mh=dF&mm=31%2C29&mn=sn-u0g3jxaa-n5fl%2Csn-nv47lnsd&ms=au%2Crdu&mv=m&mvi=6&pl=24&pcm2=yes&initcwndbps=1035000&vprv=1&mime=video%2Fmp4&ns=CG1xG_s8KRkLtsxBJMEF2NIF&gir=yes&clen=11773185&ratebypass=yes&dur=182.532&lmt=1540930908202011&mt=1607040758&fvip=2&c=WEB&txp=5431432&n=3uOEOpBOw_gU7ToP5&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgfyLaBTQ5vysRiWCrlfK-9Po-4kn4tayXcdFSzcU0BDMCIEYaCczotXXwNXqX7Vfcl3U4Ofjasgt0PynQtlUtq6jQ&sig=AOq0QJ8wRgIhALrgDY1aqV3oKu1fGR5O1kG59a3SwKOS0z3jgiVTv592AiEAwysdv3Xqn45XU7BZ2TuB9qWtyYMfDNTizqzSeSR712s="
    }
  ]
}
"""

print(yt.tablo())
"""
tabulate verisi döndürür.

+-------------+---------------------------+--------------------+------------+-----------+------------------------------------------------------+-----------------------------------------------------+----------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| sahip       | baslik                    | sure               | tarih      |   izlenme | resim                                                | aciklama                                            | kalite   | boyut    | url                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|-------------+---------------------------+--------------------+------------+-----------+------------------------------------------------------+-----------------------------------------------------+----------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| melek mosso | Ah be Aysel - Full Libido | 3 dakika, 3 saniye | 09-06-2017 |   2759361 | https://i.ytimg.com/vi/Kj26pD3uqn0/maxresdefault.jpg | Buram buram kadın kokan şarkılarla karşınızdayız :) | 360p     | 11.23 MB | https://r6---sn-u0g3jxaa-n5fl.googlevideo.com/videoplayback?expire=1607062757&ei=hYDJX5z7E8-cgQfz8o-IBg&ip=176.227.67.18&id=o-AKNCEhdBVxmQnp75jl46ZET7tpAVzJ9XU5RXaJyEZLDB&itag=18&source=youtube&requiressl=yes&mh=dF&mm=31%2C29&mn=sn-u0g3jxaa-n5fl%2Csn-nv47lnsd&ms=au%2Crdu&mv=m&mvi=6&pl=24&pcm2=yes&initcwndbps=1035000&vprv=1&mime=video%2Fmp4&ns=CG1xG_s8KRkLtsxBJMEF2NIF&gir=yes&clen=11773185&ratebypass=yes&dur=182.532&lmt=1540930908202011&mt=1607040758&fvip=2&c=WEB&txp=5431432&n=3uOEOpBOw_gU7ToP5&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgfyLaBTQ5vysRiWCrlfK-9Po-4kn4tayXcdFSzcU0BDMCIEYaCczotXXwNXqX7Vfcl3U4Ofjasgt0PynQtlUtq6jQ&sig=AOq0QJ8wRgIhALrgDY1aqV3oKu1fGR5O1kG59a3SwKOS0z3jgiVTv592AiEAwysdv3Xqn45XU7BZ2TuB9qWtyYMfDNTizqzSeSR712s= |
|             |                           |                    |            |           |                                                      | Söz-müzik : Melek Mosso                             |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | Gitar : Veys Colak                                  |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | Klip  Yönetmenİ  :  Cansu İnceay                    |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      |                                                     |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | FULL LİBİDO                                         |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      |                                                     |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | Kaç gündür gelcem dedin gelmedin                    |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | Çok içsem de kimseye vermedim                       |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | Israr ettim şansımı zorladım                        |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | Sabaha kadar ağladım duymadın                       |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      |                                                     |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | Bana hödö hödö yapma, çocuk mu var karşında         |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | Sev beni daha ne diyim, söz hiç karışmam sana       |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | Ben boşa trip atmam ama hormonlarım coştu           |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | Şu sıralar full libido, şu sıralar full libido      |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      |                                                     |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | Odamı temizledim süsüm püsüm hep sana               |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | İçli köfte yaptım tadına baksana                    |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | Bugün de aradım gelmezsen ayıp ama                  |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | Çalışkan çocuksun maşallah sana                     |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      |                                                     |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|             |                           |                    |            |           |                                                      | M.Mosso                                             |          |          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
+-------------+---------------------------+--------------------+------------+-----------+------------------------------------------------------+-----------------------------------------------------+----------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
"""

print(yt.anahtarlar)
"""
kullanılan anahtar listesini döndürür.

['sahip', 'baslik', 'sure', 'tarih', 'izlenme', 'resim', 'aciklama', 'kalite', 'boyut', 'url']
"""